# Due to Vercel needing this backend to be fully independent, we can't have anything from the workspace

[package]
name = "reweave"
version = "0.1.0"
edition = "2024"
description = "Common + backend package. Data + Deals with getting from and creating a puzzle to the server."

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"

serde_urlencoded = "0.7.1"
uuid = "1.23.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
http-body-util = "0.1.3"
hyper = { version = "1", features = ["http1", "server"] }
hyper-util = { version = "0.1", features = ["tokio"] }
dotenvy = "0.15"
jsonwebtoken = "9"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
vercel_runtime = "2"
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread"] }
sqlx = { version = "0.8.6", default-features = false, features = ["derive", "postgres", "runtime-tokio-rustls", "uuid"] }

[lib]
path = "src/lib.rs"

[[bin]]
name = "health"
path = "api/health.rs"

[[bin]]
name = "create"
path = "api/create.rs"

[[bin]]
name = "puzzle"
# path = "api/puzzle/[id].rs"
path = "api/puzzle.rs"

[[bin]]
name = "puzzles"
path = "api/puzzles.rs"

[[bin]]
name = "stats"
path = "api/stats.rs"

[[bin]]
name = "profile"
path = "api/profile.rs"

[[bin]]
name = "me"
path = "api/me.rs"

[[bin]]
name = "local-backend"
path = "src/bin/local_backend.rs"

[[bin]]
name = "update-puzzle-answers"
path = "src/bin/update_puzzle_answers.rs"
